### ISSUE TITLE
timezone-olson-0.1.8 does not compile with GHC 8.4.1

### ISSUE THREAD

**Issue by peti** [ygale/timezone-olson#5]
~~~
Data/Time/LocalTime/TimeZone/Olson/Types.hs:74:10: error:
    • No instance for (Semigroup OlsonData)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid OlsonData’
   |
74 | instance Monoid OlsonData where
   |          ^^^^^^^^^^^^^^^^
~~~

See https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid for details.

**Comment by ygale** [comment]
Fixed in 7226ad8ddabe2215f751d6e618217d806525cffe.
